export const colAdminPage = [
  {
    title: "Nombre",
    dataIndex: "name",
    key: "name",
  },
  {
    title: "Apellido",
    dataIndex: "lastname",
    key: "lastname",
  },
  {
    title: "Teléfono",
    dataIndex: "phone",
    key: "phone",
  },
  {
    title: "División",
    dataIndex: "division",
    key: "division",
  },
  {
    title: "Subdivisión",
    dataIndex: "subdivision",
    key: "subdivision",
  },
  {
    title: "Email",
    dataIndex: "email",
    key: "email",
  },
  { title: "Action", dataIndex: "action", key: "action" },
];

export const colConsultorPage = [
  {
    title: "Nombre",
    dataIndex: "name",
    key: "name",
  },
  {
    title: "Apellido",
    dataIndex: "lastname",
    key: "lastname",
  },
  {
    title: "Teléfono",
    dataIndex: "phone",
    key: "phone",
  },
  {
    title: "División",
    dataIndex: "section",
    key: "section",
  },
  {
    title: "Email",
    dataIndex: "email",
    key: "email",
  },
];

export const formData = [
  {
    key: 1,
    label: "Nombre:",
    type: "text",
    placeholder: "Nombre del consultor",
    regist: "name",
    isDisabled: false,
    isRequired: true,
    isPattern: null,
    isMaxLength: null,
    isMinLength: 3,
    patternMsg: "",
    lengthMsg: "El nombre debe tener 3 caracteres como mínimo.",
  },
  {
    key: 2,
    label: "Apellido:",
    type: "text",
    placeholder: "Apellido del consultor",
    regist: "surname",
    isDisabled: false,
    isRequired: true,
    isPattern: null,
    isMaxLength: null,
    isMinLength: 3,
    patternMsg: "",
    lengthMsg: "El apellido debe tener 3 caracteres como mínimo.",
  },
  {
    key: 3,
    label: "Teléfono:",
    type: "tel",
    placeholder: "Teléfono del consultor",
    regist: "phone",
    isDisabled: false,
    isRequired: true,
    isPattern: /^[0-9]+$/,
    isMaxLength: null,
    isMinLength: 9,
    patternMsg: "El teléfono debe contener sólo números.",
    lengthMsg: "El teléfono debe tener 9 dígitos como mínimo.",
  },
  {
    key: 4,
    label: "Email:",
    type: "text",
    placeholder: "Email del consultor",
    regist: "email",
    isDisabled: false,
    isRequired: true,
    isPattern: /^([a-z0-9]+)[._-]?([a-z0-9]?)+[@][a-z]+[.][a-z]+[.]?[a-z]+$/,
    isMaxLength: null,
    isMinLength: null,
    patternMsg: "Debe ingresar un email válido.",
    lengthMsg: "",
  },
  {
    key: 5,
    label: "Contraseña:",
    type: "text",
    placeholder: "Contraseña del consultor",
    regist: "password",
    isDisabled: false,
    isRequired: true,
    isPattern: null,
    isMaxLength: 8,
    isMinLength: 8,
    patternMsg: "",
    lengthMsg: "La contraseña debe tener 8 caracteres.",
  },
];

export const formLoginData = [
  {
    key: 1,
    label: "Correo electrónico:",
    type: "text",
    regist: "email",
    placeholder: "",
    isDisabled: false,
    isRequired: true,
    isPattern: /^([a-z0-9]+)[._-]?([a-z0-9]?)+[@][a-z]+[.][a-z]+[.]?[a-z]+$/,
    isMaxLength: null,
    isMinLength: null,
    patternMsg: "Debe ingresar un email válido.",
    lengthMsg: "",
  },
  {
    key: 2,
    label: "Contraseña:",
    type: "password",
    regist: "password",
    placeholder: "",
    isDisabled: false,
    isRequired: true,
    isPattern: null,
    isMaxLength: 8,
    isMinLength: 8,
    patternMsg: "",
    lengthMsg: "La contraseña debe tener 8 caracteres.",
  },
];

export const editConsultor = [
  {
    key: 1,
    label: "Nombre:",
    type: "text",
    placeholder: "",
    regist: "name",
    isDisabled: true,
    isRequired: true,
    isPattern: null,
    isMaxLength: null,
    isMinLength: 3,
    patternMsg: "",
    lengthMsg: "El nombre debe tener 3 caracteres como mínimo.",
  },
  {
    key: 2,
    label: "Apellido:",
    type: "text",
    placeholder: "",
    regist: "surname",
    isDisabled: true,
    isRequired: true,
    isPattern: null,
    isMaxLength: null,
    isMinLength: 3,
    patternMsg: "",
    lengthMsg: "El apellido debe tener 3 caracteres como mínimo.",
  },
  {
    key: 3,
    label: "Teléfono:",
    type: "tel",
    placeholder: "",
    regist: "phone",
    isDisabled: false,
    isRequired: true,
    isPattern: /^[0-9]+$/,
    isMaxLength: null,
    isMinLength: 9,
    patternMsg: "El teléfono debe contener sólo números.",
    lengthMsg: "El teléfono debe tener 9 dígitos como mínimo.",
  },
  {
    key: 4,
    label: "División:",
    type: "text",
    placeholder: "",
    regist: "division",
    isDisabled: true,
    isRequired: true,
    isPattern: null,
    isMaxLength: null,
    isMinLength: null,
    patternMsg: "",
    lengthMsg: "",
  },
  {
    key: 5,
    label: "Subdivisión:",
    type: "text",
    placeholder: "",
    regist: "subdivision",
    isDisabled: true,
    isRequired: true,
    isPattern: null,
    isMaxLength: null,
    isMinLength: null,
    patternMsg: "",
    lengthMsg: "",
  },
  {
    key: 6,
    label: "Email:",
    type: "text",
    placeholder: "",
    regist: "email",
    isDisabled: false,
    isRequired: true,
    isPattern: /^([a-z0-9]+)[._-]?([a-z0-9]?)+[@][a-z]+[.][a-z]+[.]?[a-z]+$/,
    isMaxLength: null,
    isMinLength: null,
    patternMsg: "Debe ingresar un email válido.",
    lengthMsg: "",
  },
  {
    key: 7,
    label: "Contraseña:",
    type: "text",
    placeholder: "",
    regist: "password",
    isDisabled: false,
    isRequired: true,
    isPattern: null,
    isMaxLength: 8,
    isMinLength: 8,
    patternMsg: "",
    lengthMsg: "La contraseña debe tener 8 caracteres.",
  },
];
